### ISSUE TITLE
Not able to apply shader

### ISSUE THREAD

**Issue by thegodtroynaar** [Eldeston/Super-Duper-Vanilla#2]
I am not able to apply the shader to mcpe 1.16.201.01
How do I apply it?
Please help.

**Comment by NickGenghar** [comment]
Wrong shader pack. The one you're looking for is ESTN Shaders from MCPEDL: https://mcpedl.com/estn-shaders/

**Comment by thegodtroynaar** [comment]
It's for JAVA...not bedrock???

**Comment by thegodtroynaar** [comment]
And ESTN IS NOT WORKING ANYMORE IN BEDROCK AS THE RENDER ENGINE CHANGED IN NEWER VERSIONS ABOVE 1.16...I HAVE MCPE 1.16.201.01

**Comment by NickGenghar** [comment]
> It's for JAVA...not bedrock???

Yes this one is for Java Edition. Are you on Windows 10 edition?

**Comment by Eldeston** [comment]
@thegodtroynaar This shader is for Minecraft Java Optifine as it is clearly stated in the description...please read the description rather than assuming.

**Comment by Eldeston** [comment]
> And ESTN IS NOT WORKING ANYMORE IN BEDROCK AS THE RENDER ENGINE CHANGED IN NEWER VERSIONS ABOVE 1.16...I HAVE MCPE 1.16.201.01

You can downgrade Mineraft Bedrock back to 1.16.4 or any version that isn't above or is 1.16.201 and experience it again.

**Comment by the-noob-coder69** [comment]
Sed
