### ISSUE TITLE
[Bug] Black Sky

### ISSUE THREAD

**Issue by KiloTensa** [Eldeston/Super-Duper-Vanilla#22]
when i use the shaders, the sky looks completely black, and i don't know how to fix it

The images with the sample and the technical information are here:

https://media.discordapp.net/attachments/908106264251351116/1086874129292075079/2023-03-18_23.43.05.png?width=829&height=468

https://media.discordapp.net/attachments/908106264251351116/1086874128683913226/2023-03-18_23.42.57.png?width=829&height=468

AMD Athlon 3000G with Vega 3 Graphics
Iris 1.5.1
Lastest shader version (1.3.3)

**Comment by Eldeston** [comment]
Is this issue persistent in Minecraft versions 1.18.2+? Have you recently updated your graphics driver? Try using Iris 1.5.2 and see if the issue persists.

**Comment by Eldeston** [comment]
Also, did SDV work as intended in previous versions such as 1.3.1 or 1.3.0?

**Comment by maksunity** [comment]
Black sky too. Version 1.19.2

**Comment by Eldeston** [comment]
> Black sky too. Version 1.19.2

Iris 1.5.2?

**Comment by Eldeston** [comment]
Does the issue also occur with Optifine?

**Comment by maksunity** [comment]
> Does the issue also occur with Optifine?

With rubidium and oculus

**Comment by Eldeston** [comment]
This shader does not support Oculus or Rubidium.

What I'm asking, however, is if this issue persists with Optifine?

**Comment by Eldeston** [comment]
Need an update on the issue otherwise I'll have to close this post.

**Comment by Eldeston** [comment]
Rubidium and Oculus are not supported for this shader. Closing issue.
