### ISSUE TITLE
[Bug] Graphic Driver Crash - 1.19.2 Fabric

### ISSUE THREAD

**Issue by Huetete** [Eldeston/Super-Duper-Vanilla#23]
This is only happening with this shaders. I find this very odd since this is the best shaders for my current build; runs smoothly between 50-60 FPS. Afther doing anything for a while, the screen will freeze and later the screen will turn into pitch black, although you can still hear the game's running. Then a white screen is shown, and the game will crash without reports.

**Desktop (please complete the following information):**
 - AMD Radeon R5 340X
 - Iris 1.5.2
 - Super Duper Vanilla 1.3.3

**Comment by Eldeston** [comment]
This appears to be an AMD issue rather than the shader's issue.

**Comment by Eldeston** [comment]
Reopening issue in response to this comment
https://www.curseforge.com/minecraft/customization/super-duper-vanilla-shaders#c113

**Comment by Huetete** [comment]
Here is a log 
[latest.txt](https://github.com/Eldeston/Super-Duper-Vanilla/files/11143146/latest.txt)

**Comment by Eldeston** [comment]
A file would have suffice instead as it's not quite convenient to read through all these...

Also, did you load Minecraft with only Iris or Iris + Fabric for this test? That way we'll know whether it's a mod issue or not.
You should also delete latest.log before loading the game so it will generate a fresh one.

**Comment by Huetete** [comment]
I think you need fabric to run Iris though. But yeah it's with both Fabric + Iris

**Comment by Eldeston** [comment]
Could you check the date on which you've recently updated your graphics driver?

The guide below for checking driver version and driver date is from Intel's, but the idea should be the same.
https://www.intel.com/content/www/us/en/support/articles/000005589/graphics.html

The one you're looking for is driver date and version.

**Comment by Huetete** [comment]
> Could you check the date on which you've recently updated your graphics driver?
> 
> The guide below for checking driver version and driver date is from Intel's, but the idea should be the same. https://www.intel.com/content/www/us/en/support/articles/000005589/graphics.html
> 
> The one you're looking for is driver date and version.

I updated to the last driver like two weeks ago. The last one seems buggy so I changed to a previous version that was more stable and worked with this shaders' previous versions

**Comment by Eldeston** [comment]
Aha, so it was an AMD update issue, is your current driver version "fixed" when using Super Duper Vanilla 1.3.3?

**Comment by Huetete** [comment]
If you mean what I think, the current driver I'm using keeps crashing whenever I use the last shaders' version. I tried the latest driver and previous but the problem persist.

**Comment by Eldeston** [comment]
Hmmmm, then I'm unsure what may have caused the issue. Try updating everything such as Iris (a recent version got out) and Sodium and use the latest graphics driver update.

**Comment by Eldeston** [comment]
Hello, has there been an update on this issue? Is it fixed?

**Comment by Huetete** [comment]
Hello! Sorry for the very late reply. I did change my PC so now I won't get this problem anymore. I'm still using the same AMD Interface, but it's fine right now. Thank you tho!

**Comment by Eldeston** [comment]
In that case, I'll assume this case closed.
