### ISSUE TITLE
[Suggestion] Option to turn off sky reflections

### ISSUE THREAD

**Issue by TorrentIvy** [Eldeston/Super-Duper-Vanilla#28]
The moon reflection and star reflections can work if using the shader as is but I don't like reflections and such and do to my tweaks, they don't fit much at all. 

![2023-05-21_23 24 37](https://github.com/Eldeston/Super-Duper-Vanilla/assets/92638054/ef0ba22e-e5d4-4363-876a-60010976d332)
![2023-05-21_23 17 56](https://github.com/Eldeston/Super-Duper-Vanilla/assets/92638054/568ac977-9201-4318-a905-fe9f906b7e2b)
![2023-05-21_23 18 08](https://github.com/Eldeston/Super-Duper-Vanilla/assets/92638054/736ce998-9afe-4eaa-8c76-de02a08ade38)

A toggle to disable these or at least adjust and play around with them would be nice. 

Honestly, I don't mind the stars all that much but the moon reflection doesn't work at all for the vanilla moon.

**Comment by Eldeston** [comment]
Allow me to refer back to this specific issue #31 as what you've mentioned is not about the sky reflection but specular reflection. However, I will give an option to disable specular reflections.
