### ISSUE TITLE
Bad visual artefacts on OptiFine pre-29 for 1.17.1

### ISSUE THREAD

**Issue by robertfwallis** [Eldeston/Super-Duper-Vanilla#3]
I imagine this is OptiFine's fault since it's obviously a pre-release, but I figured it may be worth investigating if not...

**Comment by Eldeston** [comment]
Better to post bugs that are on the **stable** versions of Optifine and not the pre-release. It's not worth it to investigate something that's a bug exclusive to Optifine's pre-releases in which are known to be unstable.
