### ISSUE TITLE
[Suggestion] Toggle entity shadows

### ISSUE THREAD

**Issue by owosoup** [Eldeston/Super-Duper-Vanilla#32]
I noticed entities would always have shadows on, and that consumes GPU resources badly with many at once

A toggle/switch for rendering entity shadows (or taking into consideration entities at all for shadowmapping) would fix that

[Alternative fix] : Have a hardcoded rule to not shadowmap entities in a forked shader version/file

_This shader is one of my favourites because you can set the shadow resolution really low and the shadow range high. to have realistic atmospheric lighting, no shader does that except this one at my knowledge. All the other options tank performance with higher minimum shadow resolutions (complementary reimagined included) and that really sucks. If this shader could disable entity shading this would be not only great for visuals but also performance. I hope it's possible, considering how differently it functions from typical methods. Kudos for your work:)_

**Comment by Eldeston** [comment]
Suggestion has been added and prepared for 1.3.4, closing issue.
