### ISSUE TITLE
[Bug] Black Sky :D

### ISSUE THREAD

**Issue by expectcube** [Eldeston/Super-Duper-Vanilla#42]
when i use the shaders, the sky looks completely black, and i don't know how to fix it

The images with the sample and the technical information are here:

![IMG-20230921-WA0037.jpg](https://github.com/Eldeston/Super-Duper-Vanilla/assets/132090999/5e320bc5-0563-47be-94bc-5731c65331b6)

![IMG-20230921-WA0036.jpg](https://github.com/Eldeston/Super-Duper-Vanilla/assets/132090999/e06e5543-8147-4951-891d-f725b19178b0)

Spec 

 - Processor : AMD Ryzen 3 3250U with Radeon Graphics 2.60 GHz
 - Ram: 8.00 GB -
 - System type : 64-bit operating system, x64-based processor
 - GPU : Radeon RX vega 3 (Integrated)
 - Shader loader : Optifine HD H9_Pre4 Ultra
 - Shader version : 1.3.4

**Comment by Eldeston** [comment]
Hello, please use the stable versions of Optifine and not the pre-release versions.

**Comment by expectcube** [comment]
> Hello, please use the stable versions of Optifine and not the pre-release versions.

okay, but I use Tlauncher, is there any other solution?

**Comment by Eldeston** [comment]
Then I'll have to close this issue post. TLauncher is not supported for piracy reasons.

Your only solution is to buy Minecraft.
