### ISSUE TITLE
[Suggestion] Add a exposure slider to prevent this problem here

### ISSUE THREAD

**Issue by atchimgripo** [Eldeston/Super-Duper-Vanilla#43]
when you get into dark areas, they get darker, this affects places like this one on the image and caves, making 'em almost unplayable

A solution to that problem would be adding a slider to control the shader's exposure
![2023-10-11_22 57 07](https://github.com/Eldeston/Super-Duper-Vanilla/assets/127154966/603782da-72df-46b9-ac48-cb0340b0ff68)

**Comment by Eldeston** [comment]
This not due to exposure but rather to cover up the sky when the player is underground.

**Comment by atchimgripo** [comment]
> This not due to exposure but rather to cover up the sky when the player is underground.

So.. can you add a way to turn that off? Caves can be darker than you might think, making using this shaders a disadvantage

**Comment by Eldeston** [comment]
This effect only simply darkens the skybox and nothing else and does not darken caves.

I'm currently considering on adding an option to turn it off or other alternatives to hide the sky when the player is in a cave.

**Comment by Eldeston** [comment]
Hello, please don't close this issue until I have fully implemented the toggle.

This post will serve me as a reminder whenever I have the opportunity to implement it.
