### ISSUE TITLE
no sun, allways night

### ISSUE THREAD

**Issue by progenit** [Eldeston/Super-Duper-Vanilla#47]
**Describe the bug**
there is no day night cycle, it always apears to be night even if /time set day aplyed

its just a normal world with the default resourepacks 

![image](https://github.com/Eldeston/Super-Duper-Vanilla/assets/78099168/7b939c44-d8f8-4bc8-8527-d119716558b6)

**Desktop (please complete the following information):**
 - GPU-- nvidia GTX 1050 ti 4GB ram
 - Shader loader--- rubidium / oculus
 - Shader version---- LAST

**Comment by Eldeston** [comment]
You're on an older verision of Oculus, use the latest version in your respective Minecraft version.
