### ISSUE TITLE
I Cant Install The Shader And When I Install The Installer, The Installer Does Nothing.

### ISSUE THREAD

**Issue by TheGooberGavin** [Eldeston/Super-Duper-Vanilla#51]
When I install the mod and go to run a Minecraft world, the shader doesn't load.

1. Install the shader, api, and run the launcher
2. Load a world
3. No shader shows up in the world

**Expected behavior**
After i install the shader and api, i expected to load up a world and have the shader on the world.

 - GPU [NVidia]
 - Shader loader [silk-API]
 - Shader version [1.20.4]

**Comment by Eldeston** [comment]
...Silk API is not a shader loader, Optifine and Iris are shader loaders that Super Duper Vanilla supports.

**Comment by TheGooberGavin** [comment]
oh
