### ISSUE TITLE
Make an option to remove realistic water and moon and sun like story mode clouds smart thing you did but I don't like realistic water!

### ISSUE THREAD

**Issue by FuriousBits** [Eldeston/Super-Duper-Vanilla#53]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Eldeston** [comment]
Can you please elaborate what you're trying to say in this post? Otherwise this post will be closed in a few days.

**Comment by Eldeston** [comment]
Issue closed.

**Comment by Felix14-v2** [comment]
> Can you please elaborate what you're trying to say in this post?

I guess they want water without waves... but didn't realised that there were settings for this
![image](https://github.com/Eldeston/Super-Duper-Vanilla/assets/75726196/9d48a434-76c0-4105-98ef-1c95deb2b00d)

Right @FuriousBits ?

**Comment by Vinson8970** [comment]
> > Can you please elaborate what you're trying to say in this post?
> 
> I guess they want water without waves... but didn't realised that there were settings for this ![image](https://github.com/Eldeston/Super-Duper-Vanilla/assets/75726196/9d48a434-76c0-4105-98ef-1c95deb2b00d)
> 
> Right [@FuriousBits](https://github.com/FuriousBits) ?

How did you find this setting? I can't find it anywhere
