### ISSUE TITLE
[Mod compatibility] In-world text does not render with Caxton present

### ISSUE THREAD

**Issue by PencilVoid** [Eldeston/Super-Duper-Vanilla#54]
**Describe the compatibility issue**
In-world text (such as nameplates and signs) does not render if the mod [Caxton](https://modrinth.com/mod/caxton) is loaded and a resource pack that adds a Caxton font is enabled.

**To Reproduce**
1. Install Caxton and Iris.
2. Install a resource pack that adds a Caxton font, such as [Atkinson Hyperlegible](https://modrinth.com/resourcepack/atkinson-hyperlegible).
3. Activate this shader pack.
4. Look at a nameplate.
5. See error.

**Expected behavior**
Nameplates and other in-world text is visible.

**Screenshots**
![2024-02-08_23 34 32](https://github.com/Eldeston/Super-Duper-Vanilla/assets/83508866/24bd01ef-9b48-423b-b64f-136783d53d03)

**Desktop (please complete the following information):**
 - GPU: Intel Iris Xe Graphics
 - Shader loader: Iris 1.6.14
 - Shader version 1.3.5
 - Mod/modpack: Custom modpack

**Additional context**
Only happens if a resource pack that adds a Caxton font is enabled. If Caxton is loaded without a font it works fine.

**Comment by Eldeston** [comment]
Does this issue appear in other shaders?

**Comment by NickGenghar** [comment]
To add, does the same issue appeared in other shaders pack or no?

**Comment by PencilVoid** [comment]
I've noticed the same issue occurs with other shaders so it's probably an issue on Caxton's end.

**Comment by Eldeston** [comment]
If that is the case, please report this issue to the developers of Caxton instead. I will now close this post.
