### ISSUE TITLE
[Bug] Turning off Story Mode Clouds makes shader fail to load on Iris

### ISSUE THREAD

**Issue by Mukul1127** [Eldeston/Super-Duper-Vanilla#56]
**Describe the bug**
The title sums it up

**To Reproduce**
1. Turn off Story Mode Clouds
2. Iris fails

**Expected behavior**
It Works

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - GPU NVIDIA
 - Shader loader Iris 1.6.17
 - Shader version v1.3.5

**Additional context**
Iris Error:
clouds.fsh: clouds.fsh: 0(284) : error C1503: undefined variable "ANIMATION_FRAMETIME"

**Comment by LOLZSICKA** [comment]
on amd rx580 here with same issue
running iris 1.6.4 with sodium 0.4.10+build.27
shader version is 1.3.5

copied error from ingame:
```
clouds.fsh: clouds.fsh: ERROR: 0:284: 'ANIMATION_FRAMETIME' : undeclared identifier 
ERROR: 0:284: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
```

**Comment by Mukul1127** [comment]
> Hello, this issue is fixed in the latest build of Super Duper Vanilla in the 1.3.6-beta.4 branch. This issue will be closed once a release version is published.

Can confirm it works perfectly fine on beta branch
