### ISSUE TITLE
[Resource Pack compatibility] Shaders experience texture incompatibility with Faithless plants

### ISSUE THREAD

**Issue by ThatLittleCrab** [Eldeston/Super-Duper-Vanilla#57]
Describe the compatibility issue:
The grass and flower block textures have four black dots in the top corners when paired with this shaders pack.

1. Enable Faithless Resource Pack

Expected behavior:
Textures would remain protected

Hardware/Mod Ver.:
 - GPU [AMD Radeon 5500m]
 - Shader loader [Oculus mc1.20.1-1.6.15a]
 - Shader version [1.3.5]
 - Mod/modpack [Custom modpack]

Screenshots:

SDV Shaders w/ Faithless:
![SDV+Faithless](https://github.com/Eldeston/Super-Duper-Vanilla/assets/123485735/b7697af4-f954-4e22-9807-6b18a8161c94)

SDV Shaders w/ Default:
![SDV+Default](https://github.com/Eldeston/Super-Duper-Vanilla/assets/123485735/9c8023f1-c655-4dbe-a90d-8ab129770030)

Complementary Unbound w/ Faithless:
![Complementary+Faithless](https://github.com/Eldeston/Super-Duper-Vanilla/assets/123485735/b3870d4b-3363-4070-81dc-c0ad8f63b320)

**Comment by Eldeston** [comment]
It appears this issue is related to alpha testing, this can be fixed immediately.

**Comment by Eldeston** [comment]
Issue fixed in 1.3.6
