### ISSUE TITLE
[Bug] Sky turns black in buildings

### ISSUE THREAD

**Issue by Sk8erAntosha** [Eldeston/Super-Duper-Vanilla#60]
**Describe the bug**
When you walk deep into building, the lower part of sky becomes black
Similar problem explained here https://github.com/Eldeston/Super-Duper-Vanilla/issues/43

**Screenshots**
![2024-03-27_03 01 15](https://github.com/Eldeston/Super-Duper-Vanilla/assets/165103104/cd05c8c7-00e2-4caa-bb13-036c2ee8bc16)
![2024-03-27_03 01 33](https://github.com/Eldeston/Super-Duper-Vanilla/assets/165103104/8ee54526-41e7-457f-a7c4-84c4ca05658f)

**Desktop (please complete the following information):**
 - GPU NVidia
 - Shader loader **Iris**

**Comment by Eldeston** [comment]
It appears you are under an are where sky light is low. This effect's intention is to cover up the sky when chunks are not fully loaded in caves or the render distance in caves is not large enough to occlude the sky.

I understand that this effect tends to be very strong and have made the necessary changes in the latest beta build to reduce that effect.

**Comment by Sk8erAntosha** [comment]
It happens almost in every building.
It would be perfect if you add a setting to adjust that effect.
Thank you for a great job!
