### ISSUE TITLE
[Bug] Turning off Story Mode clouds makes the shader fail to load.

### ISSUE THREAD

**Issue by JemyRS** [Eldeston/Super-Duper-Vanilla#69]
**Describe the bug**
As the title describes, turning off the settings "Story Mode clouds" under Atmospherics makes the Shader fail to load. 

**To Reproduce**
1. Using the most Recent 1.21 Version of the Shader: Go to Shader Settings
2. Click on 'Atmospherics'
3. Turn off 'Story mode clouds'
4. Apply

**Expected behavior**
As I suppose, the Story mode clouds should only disable the clouds, in its place, it makes the shader's effects disappear.

**Screenshots**
With "Story Mode Clouds" on:
![2024-07-12_21 53 36](https://github.com/user-attachments/assets/798cacb4-2f48-4af0-9fa3-e2644aedf629)

With "Story Mode Clouds" off:
![2024-07-12_21 54 01](https://github.com/user-attachments/assets/0b4c90b9-5c15-4b34-af55-921e625cce9d)

**Desktop (please complete the following information):**
 - GPU: Intel
 - Shader Loader: Iris 1.7.1
 - Shader Version: 1.3.5
 - Game Version: 1.21

**Additional context**
Turning such setting off pops up a message in chat:
"The shaderpack failed to load! Please report the error to the shader developer. Copy Info"

*Info*
clouds.fsh: clouds.fsh: ERROR: 0:284: 'ANIMATION_FRAMETIME' : undeclared identifier

**Comment by Felix14-v2** [comment]
Already fixed in 1.3.6. You can try it by downloading directly from the repo:
https://github.com/Eldeston/Super-Duper-Vanilla/archive/refs/heads/master.zip
