### ISSUE TITLE
There are few visual bugs that might be worth it to address

### ISSUE THREAD

**Issue by DarkReaper231** [Eldeston/Super-Duper-Vanilla#7]
![2022-03-21_10 35 47](https://user-images.githubusercontent.com/38611351/159294104-6c19c3cf-1d42-47d1-9ab5-01e23062eecf.png)
![2022-03-21_10 35 38](https://user-images.githubusercontent.com/38611351/159294120-a6a5fd92-f7c2-4aaf-b211-a606c738c6b7.png)
![2022-03-20_21 53 02](https://user-images.githubusercontent.com/38611351/159294163-21ce0025-b176-4c71-8729-b62e5ede88d5.png)
![2022-03-20_21 53 29](https://user-images.githubusercontent.com/38611351/159294198-20855667-df71-425a-90b0-0499b3a1436c.png)

When having Bare Bones resource pack, there are weird shadows on grass, leaves and other similar foliage. When standing under tree and looking at water, there are weird visual bugs which like visually duplicates particles, hand, and other stuff. Same applies when standing further from tree but looking on water in such angle that has tree leaves in view.

**Comment by DarkReaper231** [comment]
> Subsurface scattering is being worked on atm which causes those visual oddities on the grass and other foliage. This issue can be fixed temporarily by turning off subsurface scattering under the PBR section. As for the reflections, I'm currently trying to fix that. I'll keep this issue open until I push a fix.

Disabling subsurface scattering fixed the weird repeating shadows on foliage. Thanks! But there is still the problem that looking at water while under a tree or while there are particles in a way, it gets weirdly repeated.

![2022-03-22_12 19 41](https://user-images.githubusercontent.com/38611351/159470702-9392ffa0-8d4a-4628-a9e8-8e6c855ffdab.png)

What can I disable to fix this?

**Comment by Eldeston** [comment]
That is the screen space reflections, disabling it however costs you removing the reflections. Anyway, I'll close this issue now since the sub surface scattering on trees is now resolved and you shouldn't see any weird patterns on it.
