### ISSUE TITLE
[Bug] all players are translusent

### ISSUE THREAD

**Issue by Blessedpanda239** [Eldeston/Super-Duper-Vanilla#71]
when i downloaded the shaders and booted up the game all of the players are translucent and i even tried reopening minecraft but it didnt work please help

**Comment by Eldeston** [comment]
Could you please provide a screenshot and provide system specifications?

**Comment by Blessedpanda239** [comment]
> Could you please provide a screenshot and provide system specifications?
![2024-07-23_11 38 03](https://github.com/user-attachments/assets/781e564d-4305-4423-a822-e2a901ab21b0)

**Comment by Eldeston** [comment]
Are you using Optifine or Iris? What Minecraft version are you using?

This would have been easier if you followed one of the issue templates already provided.

**Comment by Blessedpanda239** [comment]
> Are you using Optifine or Iris? What Minecraft version are you using?
> 
> This would have been easier if you followed one of the issue templates already provided.

i am using 1.20.6 optifine and what and where is the issue template already provided?

**Comment by Eldeston** [comment]
> > Are you using Optifine or Iris? What Minecraft version are you using?
> > This would have been easier if you followed one of the issue templates already provided.
> 
> i am using 1.20.6 optifine and what and where is the issue template already provided?

![image](https://github.com/user-attachments/assets/3aaa31f7-82e4-44e0-856a-a9a891c7e040)
![image](https://github.com/user-attachments/assets/f9df91c2-082d-4db5-ab6b-1633a5bd2b78)

**Comment by Eldeston** [comment]
It should be present the moment you open a new issue. I fail to understand how you could miss something so obvious...

Anyway, what Optifine version? If it's a preview version, then it's most likely Optifine's issue and not Super Duper Vanilla.

**Comment by Blessedpanda239** [comment]
> It should be present the moment you open a new issue. I fail to understand how you could miss something so obvious...
> 
> Anyway, what Optifine version? If it's a preview version, then it's most likely Optifine's issue and not Super Duper Vanilla.

i was using 1.20.6 pre but after that I have tried it with the 1.20.1 optifine and the players are still translucent, it must not be optifines problem

**Comment by Eldeston** [comment]
What Super Duper Vanilla version are you using?

**Comment by Eldeston** [comment]
You can find the version number in the shader settings, usually labeled on the top left of the shader settings screen "Super Duper Vanilla 1.x.x" beside the profile setting.

**Comment by Eldeston** [comment]
Please try this version of Super Duper Vanilla. It may contain a potential fix of the translucent entities.
https://github.com/Eldeston/Super-Duper-Vanilla/archive/refs/heads/1.3.7.zip

**Comment by Blessedpanda239** [comment]
> Please try this version of Super Duper Vanilla. It may contain a potential fix of the translucent entities. https://github.com/Eldeston/Super-Duper-Vanilla/archive/refs/heads/1.3.7.zip

Wow the mod works now, thanks for everything

**Comment by Eldeston** [comment]
If that's the case, I should push an emergency fix for 1.3.6 as soon as possible. Now closing issue.
